import { Member } from "@slack/web-api/dist/response/UsersListResponse";

export function generateUser(memberSubset: Member): Member {
  return {
    id: "U012A3CDE",
    team_id: "T012AB3C4",
    name: "spengler",
    deleted: false,
    color: "9f69e7",
    real_name: "spengler",
    tz: "Asia/Tokyo",
    tz_label: "Japan Standard Time",
    tz_offset: 32400,
    profile: {
      avatar_hash: "ge3b51ca72de",
      status_text: "Print is dead",
      status_emoji: ":books:",
      real_name: "Egon Spengler",
      display_name: "spengler",
      real_name_normalized: "Egon Spengler",
      display_name_normalized: "spengler",
      email: "spengler@ghostbusters.example.com",
      image_24: "http://placehold.jp/24x24.png",
      image_32: "http://placehold.jp/32x32.png",
      image_48: "http://placehold.jp/48x48.png",
      image_72: "http://placehold.jp/72x72.png",
      image_192: "http://placehold.jp/192x192.png",
      image_512: "http://placehold.jp/512x512.png",
      team: "T012AB3C4",
    },
    is_admin: false,
    is_owner: false,
    is_primary_owner: false,
    is_restricted: false,
    is_ultra_restricted: false,
    is_bot: false,
    updated: 1502138686,
    is_app_user: false,
    has_2fa: false,
    ...memberSubset,
  };
}
